Notes/Models/ErrorViewModel.cs
namespace Notes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Notes/Controllers/BaseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Notes.Service.Abstract;

namespace Notes.Controllers
{
    public class BaseController<Dto, Entity> : Controller
    {
        private readonly IGenericService<Dto, Entity> _genericService;
        protected readonly IMapper Mapper;

        public BaseController(IGenericService<Dto, Entity> genericService, IMapper mapper)
        {
            this._genericService = genericService;
            this.Mapper = mapper;
        }

        [HttpGet("GetAllNotes")]
        public async Task<IActionResult> GetAllAsync()
        {
            var result = await _genericService.GetAllAsync();

            if (!result.Success)
            {
                return BadRequest(result.Message);
            }
            
            if(result.Response is null)
            {
                return NoContent();
            }

            return StatusCode(201, result);
        }

        [NonAction]
        public async Task<IActionResult> GetByIdAsync(int id)
        {
            var result = await _genericService.GetByIdAsync(id);

            if (result.Success)
            {
                return StatusCode(201, result);
            }

            return BadRequest(result.Message);
        }

        [NonAction]
        public async Task<IActionResult> CreateAsync([FromBody] Dto entity)
        {
            var result = await _genericService.InsertAsync(entity);

            if (result.Success)
            {
                return StatusCode(201, result);
            }

            return BadRequest(result.Message);
        }

        [NonAction]
        public async Task<IActionResult> UpdateAsync(int id, [FromBody] Dto entity)
        {
            var result = await _genericService.UpdateAsync(id, entity);

            if (result.Success)
            {
                return StatusCode(201, result);
            }

            return BadRequest(result.Message);
        }

        [NonAction]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var result = await _genericService.RemoveAsync(id);

            if (result.Success)
            {
                return StatusCode(201, result);
            }

            return BadRequest(result.Message);
        }
    }
}

Notes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Notes.Models;
using System.Diagnostics;

namespace Notes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Notes/Controllers/NoteController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Notes.Data.Models;
using Notes.Dto;
using Notes.Service.Abstract;

namespace Notes.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class NoteController : BaseController<NoteDto, Note>
    {

        private readonly INoteService _noteService;
        public NoteController(INoteService noteService, IMapper mapper) : base(noteService, mapper)
        {
            this._noteService = noteService;
        }

        [HttpGet]
        public IActionResult ViewNotes()
        {
            var notes = _noteService.GetAllAsync();
            return View(notes.Result.Response.Where(x => x.isDeleted == false).ToList());
        }

        [HttpGet("GetNoteById")]
        public async Task<IActionResult> GetByIdAsync(int id)
        {
            var result = await _noteService.GetByIdAsync(id);

            if (result.Success)
            {
                if (result.Response.isDeleted)
                {
                    return StatusCode(201, result);
                }
                
            }

            return BadRequest(result.Message);
        }

        [HttpPost("CreateNote")]
        public async Task<IActionResult> CreateAsync([FromForm] NoteDto entity)
        {
            var result = await _noteService.InsertAsync(entity);

            if (result.Success)
            {
                return RedirectToAction("Index");
            }

            return BadRequest(result.Message);
        }

        [HttpPut("UpdateNote")]
        [Route("UpdateNote/{id:int}")]
        public async Task<IActionResult> UpdateAsync(int id, [FromBody] NoteDto req)
        {
            var future = await _noteService.GetByIdAsync(id);
            var updatedEntity = future.Response; 

            updatedEntity.Title = req.Title;
            updatedEntity.Content = req.Content;

            var result = await _noteService.UpdateAsync(id, updatedEntity);

            if (result.Success)
            {
                return StatusCode(201, result);
            }

            return BadRequest(result.Message);
        }

        [HttpDelete("DeleteNote")]
        [Route("DeleteNote/{id:int}")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var future = await _noteService.GetByIdAsync(id);
            var updatedEntity = future.Response;

            updatedEntity.isDeleted = true;

            var result = await _noteService.UpdateAsync(id, updatedEntity);

            if (result.Success)
            {
                return RedirectToAction("ViewNotes");
            }

            return BadRequest(result.Message);
        }
    }
}

Notes/Views/Home/Index.cshtml
@model Notes.Data.Models.Note;

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Notes</h1>

    <div>
        <button onclick="addNote()">Add New Note</button>
    </div>

    <div>
        <form asp-action="CreateNote" asp-controller="Note" method="POST" class="notes" id="noteInfo">
            <label asp-for="Title"></label>
            <textarea asp-for="Title" class="notebox" id="title"></textarea>

            <label asp-for="Content"></label>
            <textarea asp-for="Content" class="notebox" id="content"></textarea>

            <button>Submit</button>
        </form>
    </div>

</div>

Notes/Views/Note/ViewNotes.cshtml
@model List<Notes.Dto.NoteDto>;

@{
    ViewData["Title"] = "GetAllNotes";
}

<div class="text-center">
    <div>
        <table class="table table-responsive table-hover">
            <thead>
                <tr class="table-active">
                    <th>Title</th>
                    <th>Content</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    @foreach (var note in Model)
                    {
                        <tr>
                            <td contenteditable="true" id="editedTitle-@note.Id">@note.Title</td>
                            <td contenteditable="true" id="editedContent-@note.Id">@note.Content</td>
                            <td>
                                <button type="button" onclick="submitForm(event,@note.Id)">Update</button>
                                <a asp-controller="Note" asp-action="DeleteNote" asp-route-id="@note.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>
                            <div>
                                No Notes available at this moment!
                            </div>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

</div>

Notes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Notes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Notes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Notes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="ViewNotes">My Notes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>